# Generated by Django 4.1 on 2025-09-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='publicadas',
            new_name='publicada',
        ),
    ]
