# Generated by Django 4.1 on 2025-09-08 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografias',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
