# Generated by Django 4.1 on 2025-09-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_data_fotografias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotografias',
            new_name='data_fotografia',
        ),
    ]
